/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ConversationFlow } from "./ConversationFlow";
import { ConversationFlowCountArgs } from "./ConversationFlowCountArgs";
import { ConversationFlowFindManyArgs } from "./ConversationFlowFindManyArgs";
import { ConversationFlowFindUniqueArgs } from "./ConversationFlowFindUniqueArgs";
import { CreateConversationFlowArgs } from "./CreateConversationFlowArgs";
import { UpdateConversationFlowArgs } from "./UpdateConversationFlowArgs";
import { DeleteConversationFlowArgs } from "./DeleteConversationFlowArgs";
import { BotConfiguration } from "../../botConfiguration/base/BotConfiguration";
import { ConversationFlowService } from "../conversationFlow.service";
@graphql.Resolver(() => ConversationFlow)
export class ConversationFlowResolverBase {
  constructor(protected readonly service: ConversationFlowService) {}

  async _conversationFlowsMeta(
    @graphql.Args() args: ConversationFlowCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ConversationFlow])
  async conversationFlows(
    @graphql.Args() args: ConversationFlowFindManyArgs
  ): Promise<ConversationFlow[]> {
    return this.service.conversationFlows(args);
  }

  @graphql.Query(() => ConversationFlow, { nullable: true })
  async conversationFlow(
    @graphql.Args() args: ConversationFlowFindUniqueArgs
  ): Promise<ConversationFlow | null> {
    const result = await this.service.conversationFlow(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ConversationFlow)
  async createConversationFlow(
    @graphql.Args() args: CreateConversationFlowArgs
  ): Promise<ConversationFlow> {
    return await this.service.createConversationFlow({
      ...args,
      data: {
        ...args.data,

        botConfiguration: args.data.botConfiguration
          ? {
              connect: args.data.botConfiguration,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ConversationFlow)
  async updateConversationFlow(
    @graphql.Args() args: UpdateConversationFlowArgs
  ): Promise<ConversationFlow | null> {
    try {
      return await this.service.updateConversationFlow({
        ...args,
        data: {
          ...args.data,

          botConfiguration: args.data.botConfiguration
            ? {
                connect: args.data.botConfiguration,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ConversationFlow)
  async deleteConversationFlow(
    @graphql.Args() args: DeleteConversationFlowArgs
  ): Promise<ConversationFlow | null> {
    try {
      return await this.service.deleteConversationFlow(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => BotConfiguration, {
    nullable: true,
    name: "botConfiguration",
  })
  async getBotConfiguration(
    @graphql.Parent() parent: ConversationFlow
  ): Promise<BotConfiguration | null> {
    const result = await this.service.getBotConfiguration(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
